foods = [
    'apple', 'apricot', 'avocado', 'banana', 'bean', 'beet', 'berry',
    'biscuit', 'bread', 'broccoli', 'brownie', 'butter', 'cabbage', 'cake',
    'candy', 'carrot', 'celery', 'cheese', 'cherry', 'chocolate', 'cider',
    'cookie', 'corn', 'cracker', 'cranberry', 'cream', 'cupcake', 'date',
    'doughnut', 'eggplant', 'fig', 'fruit', 'garlic', 'grape', 'gravy',
    'honey', 'ice', 'jam', 'juice', 'kale', 'ketchup', 'kiwi', 'lemon',
    'lettuce', 'lime', 'macaroni', 'mango', 'muffin', 'mushroom', 'nectar',
    'nut', 'oat', 'olive', 'onion', 'orange', 'pancake', 'papaya', 'peach',
    'peanut', 'pear', 'pecan', 'pickle', 'pie', 'pineapple', 'plum', 'popcorn',
    'potato', 'pretzel', 'pudding', 'pumpkin', 'quinoa', 'raisin', 'raspberry',
    'rice', 'salad', 'salsa', 'sandwich', 'sauce', 'sausage', 'scone', 'soup',
    'soy', 'spaghetti', 'spinach', 'sprout', 'squash', 'steak', 'strawberry',
    'sugar', 'sushi', 'sweet', 'taco', 'tangerine', 'tea', 'toast', 'toffee',
    'tomato', 'tortilla', 'truffle', 'turkey', 'vanilla', 'vegetable',
    'walnut', 'water', 'watermelon', 'wheat', 'yogurt', 'zucchini', 'almond',
    'anchovy', 'asparagus', 'bagel', 'basil', 'beer', 'blueberry', 'bok',
    'brie', 'brisket', 'caramel', 'caraway', 'cashew', 'catfish', 'chai',
    'chamomile', 'cheesecake', 'chili', 'chip', 'chive', 'clam', 'clove',
    'cocoa', 'coconut', 'cod', 'coffee', 'cola', 'coriander', 'couscous',
    'crab', 'cucumber', 'currant', 'curry', 'dill', 'dragonfruit', 'edamame',
    'elderberry', 'endive', 'fennel', 'feta', 'filet', 'flan', 'flour',
    'fondue', 'frappe', 'fudge', 'ginger', 'gouda', 'granola', 'grapefruit',
    'green', 'grits', 'guacamole', 'gumbo', 'haddock', 'ham', 'hazelnut',
    'honeydew', 'horseradish', 'hummus', 'irish', 'jambalaya', 'jelly',
    'jerky', 'jicama', 'kohlrabi', 'kumquat', 'lamb', 'leek', 'legume',
    'lemonade', 'lentil', 'licorice', 'lobster', 'macadamia', 'marzipan',
    'meatloaf', 'medlar', 'merlot', 'milk', 'mint', 'molasses', 'mung',
    'mussel', 'nacho', 'nectarine', 'nougat', 'nutmeg', 'oatmeal', 'okra',
    'omelet', 'oregano', 'oyster', 'paprika', 'parsley', 'passionfruit',
    'pastrami', 'pea', 'penne', 'pepper', 'pistachio', 'poached',
    'pomegranate', 'pork', 'portobello', 'praline', 'prawn', 'prosciutto',
    'prune', 'pumpernickel', 'quince', 'radish', 'ramen', 'ravioli', 'relish',
    'ribeye', 'roast', 'rosemary', 'rye', 'saffron', 'sage', 'salami',
    'salmon', 'sardine', 'seaweed', 'sesame', 'shallot', 'sherbet', 'shrimp',
    'skewer', 'slaw', 'smoked', 'smoothie', 'snack', 'snap', 'sorbet',
    'sourdough', 'spanakopita', 'spice', 'sponge', 'squid', 'stew', 'sundae',
    'swiss', 'syrup', 'tagliatelle', 'tamale', 'tapenade', 'tapioca',
    'tarragon', 'tequila', 'thyme', 'tofu', 'tortellini', 'tostada', 'tuna',
    'turnip', 'udon', 'veal', 'venison', 'vermicelli', 'vinegar', 'wasabi',
    'whiskey', 'white', 'wine', 'yam', 'zest', 'ziti', 'acorn', 'adobo',
    'albacore', 'ale', 'alfalfa', 'allspice', 'amaretto', 'anise',
    'applejack', 'arrowroot', 'artichoke', 'bake', 'barbecue', 'barley',
    'bass', 'bbq', 'beef', 'beetroot', 'belgian', 'bell', 'blackberry',
    'blackcurrant', 'blood', 'boil', 'bologna', 'bran', 'brandy', 'brassica',
    'brazil', 'breadfruit', 'broil', 'brunch', 'buttercream', 'buttermilk',
    'cacao', 'candied', 'cantaloupe', 'capers', 'carne', 'cayenne',
    'celeriac', 'cheddar', 'cheeseburger', 'chestnut', 'chew', 'chicory',
    'chop', 'choux', 'chowder', 'cilantro', 'cinnamon', 'citron',
    'clementine', 'cobbler', 'confectionery', 'corned', 'corona', 'cotija',
    'crackle', 'crispy', 'crockpot', 'cuisine', 'culinary', 'cumin', 'custard',
    'cutlet', 'daikon', 'dashi', 'deli', 'delicious', 'dessert', 'deviled',
    'digest', 'dijon', 'dine', 'dip', 'dough', 'drizzle', 'eat', 'egg',
    'enchilada', 'enoki', 'entree', 'escarole', 'espresso', 'fizz', 'flambé',
    'flavor', 'food', 'fork', 'french', 'fritter', 'fry', 'gelato', 'ginseng',
    'gjetost', 'glaze', 'gochujang', 'goji', 'grain', 'gratin', 'greengage',
    'grill', 'gruyere', 'guava', 'haggis', 'halibut', 'hash', 'havarti',
    'herb', 'hibiscus', 'horchata', 'hotpot', 'iced', 'jalapeno', 'jollof',
    'knish', 'kombucha', 'kudzu', 'lager', 'lamington', 'lavender', 'liquor',
    'loquat', 'lychee', 'macaron', 'madeleine', 'mai', 'maitake', 'mandarin',
    'maraschino', 'marinate', 'marmalade', 'mascarpone', 'meat', 'melon',
    'meringue', 'mesclun', 'mince', 'mirabelle', 'miso', 'mixer', 'mole',
    'mozzarella', 'mulberry', 'mull', 'mustard', 'noodle', 'octopus', 'oil',
    'palm', 'pancetta', 'paneer', 'parmesan', 'parsnip', 'pasta', 'pastry',
    'pesto', 'pimento', 'poach', 'poppy', 'porridge', 'pot', 'preserves',
    'prickly', 'prime', 'provolone', 'quail', 'quark', 'quenepa', 'quiche',
    'recipe', 'roll', 'romaine', 'rhubarb', 'risotto', 'rocket', 'salt',
    'sangria', 'sashimi', 'sauté', 'scramble', 'sea', 'seed', 'sherry',
    'sirloin', 'slice', 'smoke', 'soda', 'sole', 'sorghum', 'soya', 'spicy',
    'sprinkle', 'sriracha', 'stir-fry', 'sultana', 'sumac', 'tamarind', 'tart',
    'tater', 'tempeh', 'trifle', 'turmeric', 'vinaigrette', 'vodka', 'wafer',
    'waffle', 'watercress', 'yakitori', 'yeast', 'yule'
]
